### ISSUE TITLE
DatePicker is always open

### ISSUE THREAD

**Issue by SergSchmal** [jdtcn/BlazorDateRangePicker#102]
The DatePicker is always open, both when you open the page and when you click the "Apply" button. See attached screenshot.
![05-04-_2024_06-11-01](https://github.com/jdtcn/BlazorDateRangePicker/assets/8280474/8c6282db-1c8f-4980-82a4-f3b5e763a54d)

**Comment by jdtcn** [comment]
Hi, please check if the css styles for the component are loaded, the component uses [css and js isolation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation), you need to make sure the isolated styles are connected:
```html
<link href="{ASSEMBLY NAME}.styles.css" rel="stylesheet">
```

**Comment by SergSchmal** [comment]
I have `<link rel="stylesheet" href="_content/BlazorDateRangePicker/daterangepicker.min.css" />` installed

**Comment by jdtcn** [comment]
It won't work like this, because since version 5 [css isolation](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation) is used. Please configure it as described in the [instructions](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation). After configuring file `_content/BlazorDateRangePicker/BlazorDateRangePicker.bundle.scp.css` will be included in your app's css bundle automatically. Or you can stay with version 4.
