### ISSUE TITLE
CSS + JS isolation - not having to add component-specific link+script tags to index.html/_Host.cshtml

### ISSUE THREAD

**Issue by hakenr** [jdtcn/BlazorDateRangePicker#56]
I will prepare a PR if you are interested.

**Comment by jdtcn** [comment]
Hi, thank you for your interest. It should be easy to implement isolation for net 5, but I haven't decided yet how to provide backward compatibility with net 3.1. Do you have any idea how to provide such compatibility?

**Comment by hakenr** [comment]
Hi. Well, why would anyone want use Blazor with net31? Just drop the net31 support. ;-)

**Comment by jdtcn** [comment]
Sorry for long delay, I was busy with work.

So, for now I see two issues with CSS isolation:

1. Net core 3.1 is supported until December 3, 2022, it'll be rude to remove its support.
2. Some users prefer to customize CSS since this library is a port of famous daterangepicker.js library and their CSS styles is compatible, this change will break their apps.

Considering this difficulties I think I'll drop 3.1 support and move to CSS isolation after NET 6 (next LTS) release later this year.
