### ISSUE TITLE
How can I make the control use the date format of the current culture, assuming the culture is correct?

### ISSUE THREAD

**Issue by szalapski** [jdtcn/BlazorDateRangePicker#63]
When I'm in en-GB culture, I'd expect to see `dd/MM/yyyy` date format, but instead I see `M/d/yyyy`.    What could be wrong here?

```razor
<text>@System.Globalization.CultureInfo.CurrentCulture</text>

<DateRangePicker 
    @ref="Picker" 
    class="form-control"
    MinDate="Filters.FiscalYearStartDate"
    MaxDate="Filters.FiscalYearEndDate.AddDays(1)"
    SingleDatePicker="@Filters.LimitToOneDate"
    OnRangeSelect="SendFiltersChanged" 
    OnMonthChanged="MonthChanged" 
    DaysEnabledFunction="DaysEnabledFunction"
    @bind-StartDate="Filters.StartDateRangeBegin"
    @bind-EndDate="Filters.StartDateRangeEnd"
    @onchange="SendFiltersChanged">
    <ButtonsTemplate>...</ButtonsTemplate></DateRangePicker>
``` 
results in output:

![image](https://user-images.githubusercontent.com/2723505/137014857-ca0849aa-22c2-4b77-8e0d-e136b8ff9d98.png)

**Comment by szalapski** [comment]
I suspect this might be related to this:  https://stackoverflow.com/questions/69542125/in-blazor-webassembly-in-a-component-how-can-i-make-datetime-tostring-use-the-d/69545067#69545067

All WebAssembly component outputs show me that DateTimeFormatInfo.CurrentInfo.ShortDatePattern == "M/d/yyyy" even though CultureInfo.CurrentCulture.Name == "en-GB". Why might that be? What sets ShortDatePattern from the culture and can I "re-initialize" it?

**Comment by szalapski** [comment]
Thanks; that's surprising. I can't go live on version 6 till it is released.  It isn't fixed in any version 5 package?

Where is DateFormat documented?

**Comment by jdtcn** [comment]
Very strange, I have never seen such a thing. What dotnet version and what kind of browser do you have? It turned out that the `DateFormat` parameter is not in the documentation, I will add it, thanks for paying attention.

You can also take full control of the picker rendering with the [`PickerTemplate`](https://blazordaterangepicker.azurewebsites.net/customInput) but this is of course not very convenient.

Later I will check how the picker behaves in the latest dotnet 5 release.
