### ISSUE TITLE
New CSS isolation no longer works with dark theme

### ISSUE THREAD

**Issue by steebn** [jdtcn/BlazorDateRangePicker#98]
In the new CSS isolation file you are hardcoding a background of `#fff`. Before it was using  bootstrap variables that would change with a dark theme.

v4.5:
![image](https://github.com/jdtcn/BlazorDateRangePicker/assets/6164079/c6676b85-38e3-4aea-922f-1ed9df95bc6a)

v5.0+
![image](https://github.com/jdtcn/BlazorDateRangePicker/assets/6164079/977dbe31-885f-4a23-a2c6-e8ee6a9ddc4b)

**Comment by jdtcn** [comment]
Hi, I didn't change the styles and styles didn't use bootstrap variables before, the only thing I think might have changed is the order of css loading on your page, because before you had to add css manually and now it is added to the bandle automatically. Please make sure that the dark theme styles are loaded after the calendar styles

**Comment by steebn** [comment]
My mistake, I thought you were using the bootstrap variables that are built in Bootstrap `v5.3.0`. I forgot that I created a css override file that I changed out the colors to the Bootstrap variables. I'll try and figure out a way to win the cascade.
